CFLAGS=-Wall -g

clean:
	rm -f CountDNA				# the indent is strictly needed

all:
	make CountDNA



# if % make    , only the toppest one will be excuted.

	# Create an all: ex1 target that will build ex1 with just the command make.
	# Read man make to find out more information on how to run it.
	# Read man cc to find out more information on what the flags -Wall and -g do.
	# Research Makefiles online and see if you can improve this one even more.
	# Find a Makefile in another C project and try to understand what it's doing.