CFLAGS=-Wall -g

all:	Complementary

Complementary:	linked.o


clean:
	rm -f Complementary linked.o

  # make can't see anything in the file for object.o,
  # but it does see an object.c file,
  # and it knows how to turn a .c into a .o, so it does that.
